server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Shanghai&useUnicode=true&charaacterEncoding=utf8
    username: 自己的数据库用户名
    password: 数据库密码
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
